# Generated by Django 3.0.14 on 2021-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.TextField(blank=True),
        ),
    ]
