# Generated by Django 3.0.14 on 2021-10-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trading',
            field=models.BooleanField(default=False),
        ),
    ]
